aliases:
    apply-beast: nix run --impure home-manager/master -- -b bak switch --flake .#bjk@beast
    fleeks: cd /home/bjk/projects/ublue/fleek/examples/high
bling: high
ejected: true
flakedir: projects/ublue/fleek/examples/high
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: beast
      os: linux
      username: bjk
unfree: true
users:
    - email: bketelsen@gmail.com
      name: Brian Ketelsen
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: bjk
