{ pkgs, misc, ... }: {
  # User Customizations
  # Generated by Fleek - do not modify

  home.packages = [
    # user selected packages
    pkgs.helix
    (pkgs.nerdfonts.override { fonts = [ "FiraCode" ]; })
  ];
}



